# ドキュメント https://golangci-lint.run/usage/configuration/
run:
  modules-download-mode: readonly
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-dirs:
    - 

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: line-number

linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - goimports
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - bodyclose
    - staticcheck
    - unconvert
    - unparam
    - revive
    - stylecheck

issues:
  exclude-rules:
    - path: chapters/chapter2/chapter2.go
      linters:
        - errcheck
        - unused
        - revive
    - path: chapters/chapter2/communication/communication.go
      linters:
        - revive
    - path: chapters/chapter3/chapter3.go
      linters:
        - errcheck
        - unused
    - path: chapters/chapter4/db/select.go
      linters:
        - errcheck
    - path: chapters/chapter4/main/*
      linters:
        - unused
        - deadcode
        - revive
