// Code generated by MockGen. DO NOT EDIT.
// Source: ./mysql/queries/interface.go

// Package queries is a generated GoMock package.
package queries

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// SelectPrefecture mocks base method.
func (m *MockInterface) SelectPrefecture() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPrefecture")
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectPrefecture indicates an expected call of SelectPrefecture.
func (mr *MockInterfaceMockRecorder) SelectPrefecture() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPrefecture", reflect.TypeOf((*MockInterface)(nil).SelectPrefecture))
}

// SelectPrefectures mocks base method.
func (m *MockInterface) SelectPrefectures() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPrefectures")
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectPrefectures indicates an expected call of SelectPrefectures.
func (mr *MockInterfaceMockRecorder) SelectPrefectures() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPrefectures", reflect.TypeOf((*MockInterface)(nil).SelectPrefectures))
}
